[package]
name = "ohboi_backend"
version = "0.1.0"
authors = ["e33 <vitaliy.svinchyak@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.0"
diesel = { version = "1.4.5", features = ["postgres", "chrono", "numeric"] }
dotenv = "0.15.0"
chrono = "0.4.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bigdecimal = { version = "0.1.2", features = ["serde"] }
html5ever = "0.25.1"
reqwest = "0.10.9"
futures = "0.3"