[workspace]
members = [
    "ohboi/daemon",
    "ohboi/http",
    "lib",
]

[profile.dev]
codegen-units = 1256

[profile.release]
overflow-checks = true
codegen-units = 1
lto = "fat"
# TODO idea coverage config