[package]
name = "ohboi_backend"
version = "0.1.0"
authors = ["e33 <vitaliy.svinchyak@gmail.com>"]
edition = "2018"

[dependencies]
postgres = "0.17"
refinery = { version = "0.4", features = ["postgres"] }
