blacklisted-names = ["foo", "bar", "her", "service", "object", "module"]
cognitive-complexity-threshold = 15
too-many-arguments-threshold = 5
type-complexity-threshold = 250
single-char-binding-names-threshold = 2
enum-variant-name-threshold = 2
too-many-lines-threshold = 40