version: "3"
services:
    ohboi_backend:
        networks:
            - shopily
        build:
            context: .
        command: bash ./run.sh
        env_file:
            - .env
        ports:
            - 8888:8888
        volumes:
            - ./:/app

    ohboi_postgres:
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
        networks:
            - shopily
        image: postgres:13.1
        logging:
            driver: "none"
        environment:
            POSTGRES_DB: ohboi
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
networks:
    shopily:
        external: false