DROP TABLE product_characteristic_int_value;
DROP TABLE product_characteristic_float_value;
DROP TABLE product_characteristic_string_value;
DROP TABLE product_characteristic;
DROP TABLE category_characteristic;
DROP TABLE characteristic;
DROP TYPE characteristic_value_type;
DROP TYPE characteristic_visualisation_type;